# Generated by Django 6.0.3 on 2026-03-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_discribe_delete_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='discribe',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Image'),
        ),
    ]
