# Generated by Django 6.0.3 on 2026-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Fulltext')),
            ],
            options={
                'verbose_name': 'discribe',
                'verbose_name_plural': 'discribes',
            },
        ),
        migrations.DeleteModel(
            name='img',
        ),
    ]
